services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  postgres_backup:
    container_name: postgres_backup
    build:
      context: ./cron-backup
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
    restart: always
    networks:
      - postgres_network
    depends_on:
      - postgres_db
    volumes:
      - ./database-backups:/backups

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
